services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass


  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
         - ./data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  node-app:
    build: .
    image: node-app:1.0
    ports:
      - '9999:9999'


